### ISSUE TITLE
Crash on network error

### ISSUE THREAD

**Issue by swemoney** [MLB-LED-Scoreboard/mlb-led-scoreboard#274]
Need to look into this. Probably a silly mistake somewhere.

```
Aug 18 06:22:03 mlb-led-scoreboard python[504]: ERROR (6:22:03): Networking Error while refreshing live game status of Cubs. 5 retries remaining.
Aug 18 06:22:03 mlb-led-scoreboard python[504]: ERROR (6:22:03): URLError: [Errno -3] Temporary failure in name resolution
Aug 18 06:22:03 mlb-led-scoreboard python[504]: Traceback (most recent call last):
Aug 18 06:22:03 mlb-led-scoreboard python[504]:   File "main.py", line 36, in <module>
Aug 18 06:22:03 mlb-led-scoreboard python[504]:     MainRenderer(matrix, data).render()
Aug 18 06:22:03 mlb-led-scoreboard python[504]:   File "/home/pi/mlb-led-scoreboard/renderers/main.py", line 57, in render
Aug 18 06:22:03 mlb-led-scoreboard python[504]:     self.__render_game()
Aug 18 06:22:03 mlb-led-scoreboard python[504]:   File "/home/pi/mlb-led-scoreboard/renderers/main.py", line 124, in __render_game
Aug 18 06:22:03 mlb-led-scoreboard python[504]:     game = self.data.advance_to_next_game()
Aug 18 06:22:03 mlb-led-scoreboard python[504]:   File "/home/pi/mlb-led-scoreboard/data/data.py", line 202, in advance_to_next_game
Aug 18 06:22:03 mlb-led-scoreboard python[504]:     preferred_overview = self.fetch_preferred_team_overview()
Aug 18 06:22:03 mlb-led-scoreboard python[504]:   File "/home/pi/mlb-led-scoreboard/data/data.py", line 154, in fetch_preferred_team_overview
Aug 18 06:22:03 mlb-led-scoreboard python[504]:     game = self.games[self.game_index_for_preferred_team()]
Aug 18 06:22:03 mlb-led-scoreboard python[504]:   File "/home/pi/mlb-led-scoreboard/data/data.py", line 215, in game_index_for_preferred_team
Aug 18 06:22:03 mlb-led-scoreboard python[504]:     return self.__game_index_for(self.config.preferred_teams[0])
Aug 18 06:22:03 mlb-led-scoreboard python[504]:   File "/home/pi/mlb-led-scoreboard/data/data.py", line 236, in __game_index_for
Aug 18 06:22:03 mlb-led-scoreboard python[504]:     attempts_remaining -= 1
Aug 18 06:22:03 mlb-led-scoreboard python[504]: UnboundLocalError: local variable 'attempts_remaining' referenced before assignment
```

**Comment by ajbowler** [comment]
Closed by #281
