### ISSUE TITLE
New installation gives "KeyError: 'preferred'" on run

### ISSUE THREAD

**Issue by t0xicchrome** [MLB-LED-Scoreboard/mlb-led-scoreboard#297]
I tried running the main.py but it always seems to error out. Almost as if it's not able to read the config.json. I can confirm that the config.json that was created by the setup is in the directory with read permissions. I am kinda stumped on this one.

Here is the error at runtime:

```
root@raspberrypi:~/mlb-led-scoreboard# sudo python main.py --led-gpio-mapping=adafruit-hat-pwm --led-cols=64 --led-rows=32 --led-chain=2 --led-brightness=60
INFO (19:34:02): MLB LED Scoreboard - v4.0.0 (128x32)
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    config = ScoreboardConfig("config", matrix.width, matrix.height)
  File "/root/mlb-led-scoreboard/data/scoreboard_config.py", line 22, in __init__
KeyError: 'preferred'
```

I ran the install again to see if it missed something, here is that log:

```
root@raspberrypi:~/mlb-led-scoreboard# ./install.sh
Running rgbmatrix installation...
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Fetched 15.0 kB in 1s (11.8 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'python-pil' instead of 'python-pillow'
python-pil is already the newest version (4.0.0-4+deb9u2).
python2.7-dev is already the newest version (2.7.13-2+deb9u4).
0 upgraded, 0 newly installed, 0 to remove and 118 not upgraded.
make -C ./lib
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/examples-api-use'
make -C ../lib
make[2]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[2]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[2]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
python setup.py build --build-lib .
running build
running build_py
running build_ext
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/bindings/python'
make -C ./lib
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/examples-api-use'
make -C ../lib
make[2]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[2]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[2]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
python setup.py build --build-lib .
running build
running build_py
running build_ext
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/bindings/python'
make -C bindings/python install
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/bindings/python'
python setup.py install
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/rgbmatrix-0.0.1.egg-info
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/bindings/python'
Obtaining file:///root/mlb-led-scoreboard/matrix/bindings/python
Installing collected packages: rgbmatrix
  Found existing installation: rgbmatrix 0.0.1
    DEPRECATION: Uninstalling a distutils installed project (rgbmatrix) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling rgbmatrix-0.0.1:
      Successfully uninstalled rgbmatrix-0.0.1
  Running setup.py develop for rgbmatrix
Successfully installed rgbmatrix
Installing required dependencies. This may take some time (10-20 minutes-ish)...
HEAD is now at 73f2be8 Bump version
M       matrix
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
libxml2-dev is already the newest version (2.9.4+dfsg1-2.2+deb9u2).
libxslt1-dev is already the newest version (1.1.29-2.1+deb9u2).
0 upgraded, 0 newly installed, 0 to remove and 118 not upgraded.
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: tzlocal in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: feedparser in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pyowm in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: geojson<2.4,>=2.3.0 in /usr/local/lib/python2.7/dist-packages (from pyowm)
Requirement already satisfied: requests<3,>=2.18.2 in /usr/local/lib/python2.7/dist-packages (from pyowm)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests<3,>=2.18.2->pyowm)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests<3,>=2.18.2->pyowm)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests<3,>=2.18.2->pyowm)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests<3,>=2.18.2->pyowm)
Uninstalling mlbgame-2.5.0:
  Successfully uninstalled mlbgame-2.5.0
Collecting mlbgame from git+git://github.com/ajbowler/mlbgame.git@#egg=mlbgame
  Cloning git://github.com/ajbowler/mlbgame.git to /tmp/pip-build-6a9RCp/mlbgame
Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from mlbgame)
Installing collected packages: mlbgame
  Running setup.py install for mlbgame ... done
Successfully installed mlbgame-2.5.0
make: 'matrix/lib/librgbmatrix.a' is up to date.
If you didn't see any errors above, everything should be installed!

You'll need a config.json file to customize your settings. If you are updating
from an older version and you were required to run this install script again or
this is a fresh install, it's recommended we make a fresh one right now.
This will create a brand new 'config.json' file with default values so edit this
file with your own settings.

Would you like to do this now? [Y/n] y

You should now have a fresh config.json file you can customize with your own settings.

Installation complete! Play around with the examples in matrix/bindings/python/samples to make sure your matrix is working.
```

**Comment by twfarley** [comment]
Can you post your config file?

**Comment by t0xicchrome** [comment]
It is the one that is automatically generated. I have not made any modifications.

```
{
	"preferred": {
		"teams": ["Cubs"],
		"divisions": ["NL Central"]
	},
	"news_ticker": {
		"team_offday": true,
		"always_display": false,
		"preferred_teams": true,
		"traderumors": true,
		"mlb_news": true,
		"countdowns": true,
		"date": true,
		"date_format": "%A, %B %-d"
	},
	"standings": {
		"team_offday": false,
		"mlb_offday": true,
		"always_display": false
	},
	"rotation": {
		"enabled": true,
		"scroll_until_finished": true,
		"only_preferred": false,
		"rates": {
			"live": 15.0,
			"final": 15.0,
			"pregame": 15.0
		},
		"while_preferred_team_live": {
			"enabled": false,
			"during_inning_breaks": false
		}
	},
	"weather": {
		"apikey": "YOUR_API_KEY_HERE",
		"location": "Chicago,il,us",
		"metric_units": false
	},
	"time_format": "12h",
	"end_of_day": "00:00",
	"full_team_names": true,
	"scrolling_speed": 2,
	"debug": false,
	"demo_date": false
}
```

**Comment by swemoney** [comment]
Config looks fine. Not sure why the specific error you're getting would be happening. I'm curious about why you're defining a 64x32 LED array in the command options but the script is detecting you have a 128x32.

**Comment by t0xicchrome** [comment]
I am using a chain of 2 64x32 panels --led-chain=2

**Comment by swemoney** [comment]
Ahhh. I missed the led-chain. Sorry about that. Would you be able to just completely delete the mlb-led-scoreboard directory and reclone/reinstall again?

**Comment by swemoney** [comment]
also, it appears you're logged into your pi as root? if that's the case, you shouldn't need the `sudo`.

**Comment by t0xicchrome** [comment]
I was copying the command from the readme. 

I have deleted the folder and redone the install.  The problem still persists
The error:

```
root@raspberrypi:~/mlb-led-scoreboard# python main.py --led-gpio-mapping=adafruit-hat-pwm --led-cols=64 --led-rows=32 --led-chain=2 --led-brightness=60
INFO (21:21:24): MLB LED Scoreboard - v4.0.0 (128x32)
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    config = ScoreboardConfig("config", matrix.width, matrix.height)
  File "/root/mlb-led-scoreboard/data/scoreboard_config.py", line 22, in __init__
KeyError: 'preferred'
```

The config file:
```
{
	"preferred": {
		"teams": ["Cubs"],
		"divisions": ["NL Central"]
	},
	"news_ticker": {
		"team_offday": true,
		"always_display": false,
		"preferred_teams": true,
		"traderumors": true,
		"mlb_news": true,
		"countdowns": true,
		"date": true,
		"date_format": "%A, %B %-d"
	},
	"standings": {
		"team_offday": false,
		"mlb_offday": true,
		"always_display": false
	},
	"rotation": {
		"enabled": true,
		"scroll_until_finished": true,
		"only_preferred": false,
		"rates": {
			"live": 15.0,
			"final": 15.0,
			"pregame": 15.0
		},
		"while_preferred_team_live": {
			"enabled": false,
			"during_inning_breaks": false
		}
	},
	"weather": {
		"apikey": "YOUR_API_KEY_HERE",
		"location": "Chicago,il,us",
		"metric_units": false
	},
	"time_format": "12h",
	"end_of_day": "00:00",
	"full_team_names": true,
	"scrolling_speed": 2,
	"debug": false,
	"demo_date": false
}
```



Here is the install log:

```
root@raspberrypi:~/mlb-led-scoreboard# ./install.sh
Running rgbmatrix installation...
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'python-pil' instead of 'python-pillow'
python-pil is already the newest version (4.0.0-4+deb9u2).
python2.7-dev is already the newest version (2.7.13-2+deb9u4).
0 upgraded, 0 newly installed, 0 to remove and 118 not upgraded.
make -C ./lib
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o gpio.o gpio.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o led-matrix.o led-matrix.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o options-initialize.o options-initialize.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o framebuffer.o framebuffer.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o thread.o thread.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o bdf-font.o bdf-font.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o graphics.o graphics.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o led-matrix-c.o led-matrix-c.cc
cc  -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -c -o hardware-mapping.o hardware-mapping.c
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o pixel-mapper.o pixel-mapper.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o multiplex-mappers.o multiplex-mappers.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o content-streamer.o content-streamer.cc
g++ -I../include -Wall -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -Wextra -Wno-unused-parameter -fno-exceptions -c -o deprecated-transformer.o deprecated-transformer.cc
ar rcs librgbmatrix.a gpio.o led-matrix.o options-initialize.o framebuffer.o thread.o bdf-font.o graphics.o led-matrix-c.o hardware-mapping.o pixel-mapper.o multiplex-mappers.o content-streamer.o deprecated-transformer.o
g++ -shared -Wl,-soname,librgbmatrix.so.1 -o librgbmatrix.so.1 gpio.o led-matrix.o options-initialize.o framebuffer.o thread.o bdf-font.o graphics.o led-matrix-c.o hardware-mapping.o pixel-mapper.o multiplex-mappers.o content-streamer.o deprecated-transformer.o -lpthread  -lrt -lm -lpthread
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/examples-api-use'
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o demo-main.o demo-main.cc
make -C ../lib
make[2]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[2]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
g++ demo-main.o -o demo -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o minimal-example.o minimal-example.cc
g++ minimal-example.o -o minimal-example -L../lib -lrgbmatrix -lrt -lm -lpthread
cc -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o c-example.o c-example.c
cc c-example.o -o c-example -L../lib -lrgbmatrix -lrt -lm -lpthread -lstdc++
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o text-example.o text-example.cc
g++ text-example.o -o text-example -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o scrolling-text-example.o scrolling-text-example.cc
g++ scrolling-text-example.o -o scrolling-text-example -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o clock.o clock.cc
g++ clock.o -o clock -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o ledcat.o ledcat.cc
g++ ledcat.o -o ledcat -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o input-example.o input-example.cc
g++ input-example.o -o input-example -L../lib -lrgbmatrix -lrt -lm -lpthread
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[2]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
python setup.py build --build-lib .
running build
running build_py
running build_ext
building 'core' extension
creating build
creating build/temp.linux-armv7l-2.7
creating build/temp.linux-armv7l-2.7/rgbmatrix
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../../include -I/usr/include/python2.7 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-2.7/rgbmatrix/core.o -O3 -Wall
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/rgbmatrix/core.o -L../../lib -lrgbmatrix -o ./rgbmatrix/core.so
building 'graphics' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../../include -I/usr/include/python2.7 -c rgbmatrix/graphics.cpp -o build/temp.linux-armv7l-2.7/rgbmatrix/graphics.o -O3 -Wall
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/rgbmatrix/graphics.o -L../../lib -lrgbmatrix -o ./rgbmatrix/graphics.so
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/bindings/python'
make -C ./lib
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/examples-api-use'
make -C ../lib
make[2]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[2]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/root/mlb-led-scoreboard/matrix/lib'
make[2]: Leaving directory '/root/mlb-led-scoreboard/matrix/lib'
python setup.py build --build-lib .
running build
running build_py
running build_ext
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/bindings/python'
make -C bindings/python install
make[1]: Entering directory '/root/mlb-led-scoreboard/matrix/bindings/python'
python setup.py install
running install
running build
running build_py
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/rgbmatrix
copying rgbmatrix/__init__.py -> build/lib.linux-armv7l-2.7/rgbmatrix
running build_ext
building 'core' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../../include -I/usr/include/python2.7 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-2.7/rgbmatrix/core.o -O3 -Wall
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/rgbmatrix/core.o -L../../lib -lrgbmatrix -o build/lib.linux-armv7l-2.7/rgbmatrix/core.so
building 'graphics' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I../../include -I/usr/include/python2.7 -c rgbmatrix/graphics.cpp -o build/temp.linux-armv7l-2.7/rgbmatrix/graphics.o -O3 -Wall
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ajc2xi/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/rgbmatrix/graphics.o -L../../lib -lrgbmatrix -o build/lib.linux-armv7l-2.7/rgbmatrix/graphics.so
running install_lib
copying build/lib.linux-armv7l-2.7/rgbmatrix/graphics.so -> /usr/local/lib/python2.7/dist-packages/rgbmatrix
copying build/lib.linux-armv7l-2.7/rgbmatrix/core.so -> /usr/local/lib/python2.7/dist-packages/rgbmatrix
copying build/lib.linux-armv7l-2.7/rgbmatrix/__init__.py -> /usr/local/lib/python2.7/dist-packages/rgbmatrix
byte-compiling /usr/local/lib/python2.7/dist-packages/rgbmatrix/__init__.py to __init__.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/rgbmatrix-0.0.1.egg-info
make[1]: Leaving directory '/root/mlb-led-scoreboard/matrix/bindings/python'
Obtaining file:///root/mlb-led-scoreboard/matrix/bindings/python
Installing collected packages: rgbmatrix
  Found existing installation: rgbmatrix 0.0.1
    DEPRECATION: Uninstalling a distutils installed project (rgbmatrix) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling rgbmatrix-0.0.1:
      Successfully uninstalled rgbmatrix-0.0.1
  Running setup.py develop for rgbmatrix
Successfully installed rgbmatrix
Installing required dependencies. This may take some time (10-20 minutes-ish)...
HEAD is now at 73f2be8 Bump version
M       matrix
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
libxml2-dev is already the newest version (2.9.4+dfsg1-2.2+deb9u2).
libxslt1-dev is already the newest version (1.1.29-2.1+deb9u2).
0 upgraded, 0 newly installed, 0 to remove and 118 not upgraded.
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: tzlocal in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: feedparser in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pyowm in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: geojson<2.4,>=2.3.0 in /usr/local/lib/python2.7/dist-packages (from pyowm)
Requirement already satisfied: requests<3,>=2.18.2 in /usr/local/lib/python2.7/dist-packages (from pyowm)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests<3,>=2.18.2->pyowm)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests<3,>=2.18.2->pyowm)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests<3,>=2.18.2->pyowm)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests<3,>=2.18.2->pyowm)
Uninstalling mlbgame-2.5.0:
  Successfully uninstalled mlbgame-2.5.0
Collecting mlbgame from git+git://github.com/ajbowler/mlbgame.git@#egg=mlbgame
  Cloning git://github.com/ajbowler/mlbgame.git to /tmp/pip-build-Jsgm60/mlbgame
Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from mlbgame)
Installing collected packages: mlbgame
  Running setup.py install for mlbgame ... done
Successfully installed mlbgame-2.5.0
make: 'matrix/lib/librgbmatrix.a' is up to date.
If you didn't see any errors above, everything should be installed!

You'll need a config.json file to customize your settings. If you are updating
from an older version and you were required to run this install script again or
this is a fresh install, it's recommended we make a fresh one right now.
This will create a brand new 'config.json' file with default values so edit this
file with your own settings.

Would you like to do this now? [Y/n] y
rm: cannot remove 'config.json': No such file or directory

You should now have a fresh config.json file you can customize with your own settings.

Installation complete! Play around with the examples in matrix/bindings/python/samples to make sure your matrix is working.

```

**Comment by swemoney** [comment]
Still not sure what would be causing it. Since most people don't ever log in as root, could you do a reinstall as the default user `pi` instead? So completely log out of the pi and log in again as just the regular old pi user.

**Comment by t0xicchrome** [comment]
The problem was the /root directory permissions.  Even as root the program runs fine as long as it is not located within the /root directory. If I try to run it in the /root directory the error happens. Seems by default the root group does not have execution permissions in this directory. Setting the folder to 0750 allowed  Should have messed around with that. Thanks for the help.
