### ISSUE TITLE
Running "sudo python main.py....." but no info comes back when updating game

### ISSUE THREAD

**Issue by KyleLosch10** [MLB-LED-Scoreboard/mlb-led-scoreboard#312]
I am able to run ```sudo python main.py --led-gpio-mapping="adafruit-hat"```

 and the response I get is 

```INFO (19:38:58): MLB LED Scoreboard - v4.0.1 (32x32) DEBUG (7:38:58): Updating games for 2/28/2021```

However, nothing shows up on the LED Screen (The LED does work because I have been able to run other scoreboards)

When I stop the command, I get the following

```Traceback (most recent call last):
  File "main.py", line 34, in <module>
    data = Data(config)
  File "/home/pi/mlb-led-scoreboard/data/data.py", line 35, in __init__
    self.refresh_games()
  File "/home/pi/mlb-led-scoreboard/data/data.py", line 93, in refresh_games
    all_games = mlbgame.day(self.year, self.month, self.day)
  File "/usr/local/lib/python2.7/dist-packages/mlbgame/__init__.py", line 151, in day
    data = mlbgame.game.scoreboard(year, month, day, home=home, away=away)
  File "/usr/local/lib/python2.7/dist-packages/mlbgame/game.py", line 19, in scoreboard
    data = mlbgame.data.get_scoreboard(year, month, day)
  File "/usr/local/lib/python2.7/dist-packages/mlbgame/data.py", line 58, in get_scoreboard
    data = urlopen(BASE_URL.format(year, month, day) + 'scoreboard.xml')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
^C    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1058, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1098, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1054, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 831, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 566, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```

I have tried uninstalling and reinstalling twice. I am using a Raspberry Pi 3B+. I am running a couple of other scoreboards (dont now if that makes a difference

Config is: (only changed debug to true)

```{
        "preferred": {
                "teams": ["Cubs"],
                "divisions": ["NL Central"]
        },
        "news_ticker": {
                "team_offday": true,
                "always_display": false,
                "preferred_teams": true,
                "traderumors": true,
                "mlb_news": true,
                "countdowns": true,
                "date": true,
                "date_format": "%A, %B %-d"
        },
        "standings": {
                "team_offday": false,
                "mlb_offday": true,
                "always_display": false
        },
        "rotation": {
                "enabled": true,
                "scroll_until_finished": true,
                "only_preferred": false,
                "rates": {
                        "live": 15.0,
                        "final": 15.0,
                        "pregame": 15.0
                },
                "while_preferred_team_live": {
                        "enabled": false,
                        "during_inning_breaks": false
                }
        },
        "weather": {
                "apikey": "YOUR_API_KEY_HERE",
                "location": "Chicago,il,us",
                "metric_units": false
        },
        "time_format": "12h",
        "end_of_day": "00:00",
        "full_team_names": true,
        "scrolling_speed": 2,
        "debug": true,
        "demo_date": false
}
```

**Comment by KyleLosch10** [comment]
Firewall on my network was causing the problem
