### ISSUE TITLE
Application Crashes on BadStatusLine(...)

### ISSUE THREAD

**Issue by jmordars** [MLB-LED-Scoreboard/mlb-led-scoreboard#323]
Had a crash over the weekend -- here is the trace I got:

```
pi@raspberrypi:~/mlb-led-scoreboard $ sudo python main.py --led-gpio-mapping="adafruit-hat" --led-cols 64 --led-slowdown-gpio 4
INFO (08:00:01): MLB LED Scoreboard - v4.0.1 (64x32)
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    MainRenderer(matrix, data).render()
  File "/home/pi/mlb-led-scoreboard/renderers/main.py", line 57, in render
    self.__render_game()
  File "/home/pi/mlb-led-scoreboard/renderers/main.py", line 132, in __render_game
    self.data.refresh_overview()
  File "/home/pi/mlb-led-scoreboard/data/data.py", line 122, in refresh_overview
    self.overview = mlbgame.overview(self.current_game().game_id)
  File "/usr/local/lib/python2.7/dist-packages/mlbgame/__init__.py", line 198, in overview
    return mlbgame.game.Overview(mlbgame.game.overview(game_id))
  File "/usr/local/lib/python2.7/dist-packages/mlbgame/game.py", line 341, in overview
    output = add_raw_box_score_attributes(output, game_id)
  File "/usr/local/lib/python2.7/dist-packages/mlbgame/game.py", line 369, in add_raw_box_score_attributes
    raw_box_score = mlbgame.data.get_raw_box_score(game_id)
  File "/usr/local/lib/python2.7/dist-packages/mlbgame/data.py", line 79, in get_raw_box_score
    'rawboxscore.xml'))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1127, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 454, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 418, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

**Comment by twfarley** [comment]
This won't be an issue with latest version.
