### ISSUE TITLE
Error after updating latest commit

### ISSUE THREAD

**Issue by phonorad** [MLB-LED-Scoreboard/mlb-led-scoreboard#346]
After updating my scoreboard using "sudo ./install.sh" for the latest commit which fixes the mlbgame issue, I am getting the following error when I run the program;
Traceback (most recent call last):
  File "/home/pi/mlb-led-scoreboard/main.py", line 15, in <module>
      from data import Data
  File "/home/pi/mlb-led-scoreboard/data/__init__.py", line 27
      self.schedule: Schedule = Schedule(self.today, config)
                          ^
SyntaxError: invalid syntax

I am getting the same error on the two boards that I have.   On one board I did not create a new config.json, on the other board I did. 

Also, the installer gave an error on the mlbgame install with "The unauthenticated git protocol on port 9418 is no longer supported", but I am assuming this is unimportant if mlbgame is no longer being used.

Thanks for any thoughts!

**Comment by phonorad** [comment]
Ok, so got it working.  I was running Raspian Stretch.  Redid the OS with latest Raspberry Pi OS (Bullseye), installed the scoreboard and it is up!  Thanks for all of the effort in getting it working with the new API!
