### ISSUE TITLE
libopenblas.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ando01** [MLB-LED-Scoreboard/mlb-led-scoreboard#543]
## This issue is a

- [ ] Bug Report

## Hardware Configuration 

- Raspberry Pi Revision 2B:
- Operating System: Tried both versions of RaspiOS based on Bookworm and Bullseye
- Matrix size: Emulated (Still working on the hardware)
- Display adapter (HAT/Bonnet/etc.):
  - Additional information:
- Power source(s): 5V 2A to Pi

## Software Configuration
Default config

- MLB LED Scoreboard Version:
- Commands/arguments used to start the scoreboard:
sudo /,.main.py --emulated

## Expected behavior
Emulated scoreboard should appear at HTTP://IP ADDRESS:8888

## Actual behavior
Error in command line:

andy@pi2mlbscoreboard:~/mlb-led-scoreboard $ sudo ./main.py --emulated
Traceback (most recent call last):
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/numpy/_core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/numpy/_core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/numpy/_core/overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/numpy/_core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/andy/mlb-led-scoreboard/venv/bin/python3"
  * The NumPy version is: "2.0.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/andy/mlb-led-scoreboard/./main.py", line 28, in <module>
    import driver
  File "/home/andy/mlb-led-scoreboard/driver/__init__.py", line 50, in <module>
    sys.modules['driver'] = DriverWrapper()
  File "/home/andy/mlb-led-scoreboard/driver/__init__.py", line 12, in __init__
    self.set_mode(DriverMode.SOFTWARE_EMULATION)
  File "/home/andy/mlb-led-scoreboard/driver/__init__.py", line 42, in set_mode
    import RGBMatrixEmulator
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/RGBMatrixEmulator/__init__.py", line 2, in <module>
    from RGBMatrixEmulator.emulators.matrix import RGBMatrix
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/RGBMatrixEmulator/emulators/matrix.py", line 1, in <module>
    from RGBMatrixEmulator.emulators.canvas import Canvas
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/RGBMatrixEmulator/emulators/canvas.py", line 1, in <module>
    import numpy as np
  File "/home/andy/mlb-led-scoreboard/venv/lib/python3.9/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

I saw a similar closed issue #529 at https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/issues/529 and tried their solution of running the rgbmatrix install process manually but it fails as well. Seems there may be a bigger issue here.

**Comment by ando01** [comment]
Some additional info. Post #529 mentions they just manually installed RGBMATRIX from the install script. Here is the sections that I found that deals with that:

if [ "$SKIP_MATRIX" = false ]; then
    echo "Running rgbmatrix installation..."
    sudo apt-get install -y make
    mkdir submodules
    cd submodules
    git clone https://github.com/hzeller/rpi-rgb-led-matrix.git matrix
    cd matrix
    git pull
    make build-python PYTHON="$PYTHON"
    sudo make install-python PYTHON="$PYTHON"


I already have the submodules and matrix folders so I tried running the make build-python PYTHON="$PYTHON" command and this is the error that occurs:

andy@pi2mlbscoreboard:~/mlb-led-scoreboard/submodules/matrix $ sudo make build-python PYTHON="$PYTHON"
make -C ./lib
make[1]: Entering directory '/home/andy/mlb-led-scoreboard/submodules/matrix/lib'
make[1]: Leaving directory '/home/andy/mlb-led-scoreboard/submodules/matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/home/andy/mlb-led-scoreboard/submodules/matrix/examples-api-use'
make -C ../lib
make[2]: Entering directory '/home/andy/mlb-led-scoreboard/submodules/matrix/lib'
make[2]: Leaving directory '/home/andy/mlb-led-scoreboard/submodules/matrix/lib'
make[1]: Leaving directory '/home/andy/mlb-led-scoreboard/submodules/matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/home/andy/mlb-led-scoreboard/submodules/matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/home/andy/mlb-led-scoreboard/submodules/matrix/lib'
make[2]: Leaving directory '/home/andy/mlb-led-scoreboard/submodules/matrix/lib'
setup.py build --build-lib .
make[1]: setup.py: No such file or directory
make[1]: *** [Makefile:67: build-python] Error 127
make[1]: Leaving directory '/home/andy/mlb-led-scoreboard/submodules/matrix/bindings/python'
make: *** [Makefile:29: build-python] Error 2

**Comment by ando01** [comment]
I decided not to use the Rpi2 so I am just going to close
